server:
  port: 8085

spring:
  grpc:
    server:
      port: 9090
  application:
    name: user_service
  flyway:
    url: jdbc:postgresql://localhost:5434/user_service_db
    user: postgres
    password: pass1234
  r2dbc:
#    url: r2dbc:postgresql://localhost:5434/user_service_db
    username: postgres
    password: pass1234
  jwt:
    secret: 8df235b60454947172088a5fe1082fcbf9cfa5b431d50216bcbdd6b03a70ff63
    accessTokenExpiration: 10
    refreshTokenExpiration: 60


logging:
  level:
    org:
      springframework:
        r2dbc: DEBUG