server:
  port: 8082

spring:
  kafka:
    bootstrap-servers:
      - "localhost:29092"
  #  config:
#    import: optional:file:.env[.properties]
  grpc:
    server:
      port: 9090
  application:
    name: user_service
  flyway:
    url: jdbc:postgresql://localhost:5434/user_service_db
    user: postgres
    password: pass1234
  r2dbc:
#    url: r2dbc:postgresql://localhost:5434/user_service_db
    username: postgres
    password: pass1234
  jwt:
    secret: ${SPRING_JWT_SECRET}
    accessTokenExpiration: 60
    refreshTokenExpiration: 60
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SPRING_GMAIL_USERNAME}
    password: ${SPRING_GMAIL_APP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


logging:
  level:
    org:
      springframework:
        r2dbc: DEBUG


totp:
  secret:
    length: 32
  time:
    discrepancy: 1